workflow:
  - detail_annotation

model:
  # base_url: OpenAI-compatible API 地址。
  # 本地 vLLM 示例：http://127.0.0.1:8002/v1
  base_url: "http://1993781598432617.cn-wulanchabu.pai-eas.aliyuncs.com/api/predict/quickstart_deploy_20260717_xtvt/v1"
  #"http://127.0.0.1:8002/v1"
  #qwen122B "http://1993781598432617.cn-wulanchabu.pai-eas.aliyuncs.com/api/predict/quickstart_deploy_20260713_olyp/v1"
  #qwen397B "http://1993781598432617.cn-wulanchabu.pai-eas.aliyuncs.com/api/predict/quickstart_deploy_20260717_xtvt/v1"

  # api_key: API key。
  # 本地 vLLM 通常可以使用 "EMPTY"。
  api_key: "YmNjODIyN2EyNTViY2ZmNmNhYzBhNDZkNzUyNTQ1NzJhMTQ5NGUxMw=="
  #"EMPTY"
  #qwen122B"OTk4NzQ4MTk1ZjQzMTQ5OTRjODIyNWQzMGQyODM5ZGVkNWEyMGQxNQ=="
  #qwen397B"Yjk0MzNhYjUyNTU3M2I3MjdkMTI0MzVkMWJhNTE2MDc3NmQ2MTM2MQ=="

  # model: 模型名称，需要与 /v1/models 返回的 id 一致。
  # 例如："Qwen3-VL-8B-Instruct"、"Qwen3-VL-30B-A3B-Instruct-FP8"。
  model: "Qwen3.5-397B-A17B-FP8"
  #"Qwen3.5-27B"
  #"Qwen3.5-122B-A10B"
  #"Qwen3.5-397B-A17B-FP8"


  max_tokens: 4096
  temperature: 0.0
  top_p: 0.95
  top_k: 0
  extra_body:
    chat_template_kwargs:
      enable_thinking: false
  max_retries: 3


stages:
  detail_annotation:
    prompt:
      module: "prompts.annotation_cn"
      system: "SUBTASK_STATE_SYSTEM_PROMPT"
      user: "SUBTASK_STATE_USER_PROMPT"
    output_key: "detail_annotation"
    generation:
       max_tokens: 16384
    video:
      input_mode: "image_sequence"
      add_frame_tags: true
      max_time: -1
      save_processed: true
      fps: 1.0
      max_frames: 172
      resize_width: 672
      jpeg_quality: 95
      draw_timestamps: true
      draw_view_names: false
      draw_montage_axes: false
      min_api_frames: 12
      merge_views: false
      merge_mode: "per_frame"
      merge_length: -1
      view_names:
        - main_view
